### ISSUE TITLE
Configuration file for default values

### ISSUE THREAD

**Issue by TheFiZi** [ziirish/zerocli#1]
A way to have a /etc/zero-cli.conf or even just a config file in the directory with the script that lets you set default values so running the command can be as simple as:

"cat /var/log/http.log | zerocli.sh"

or as complicated as

"cat /var/log/http.log | zerocli.sh -S https://paste.somewhere.com -o -s -e 10min"

**Comment by ziirish** [comment]
Hi,

It's a great idea. I'll add that very soon.

**Comment by ziirish** [comment]
done

https://github.com/ziirish/zerocli/commit/40f0e343d6e2a5d89cb5a0b22b5c03c2fbdbefda
