### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by Erkalos** [ziirish/zerocli#10]
Hi all,

I want to use it but I don't know how to install just clone and use the script ?

**Comment by ziirish** [comment]
Hello,

You'll need a javascript engine (I successfully tested rhino and d8, see
[README](README.md))

After that, you just need to clone the repo, edit your configuration (a
[sample](zerocli.conf.sample) is provided) and your good to go :)

**Comment by Erkalos** [comment]
sorry delay,

Ok but how i can install rhino or d8 ?

**Comment by ziirish** [comment]
Well, it depends what distribution you are running...

**Comment by Erkalos** [comment]
Centos

**Comment by ziirish** [comment]
Maybe run `yum install rhino`?

There are hundreds of Linux distrib out there so I'm afraid I cannot describe exactly how to setup each one of them.
