### ISSUE TITLE
File size limitations?

### ISSUE THREAD

**Issue by TheFiZi** [ziirish/zerocli#5]
Any idea what the limits are for file uploads? and how to increase it?

```
[root@localhost log]# zerocli.sh -f yum.log

Encrypting data... [done]
[e] Error: server returned 100
200
[root@localhost log]# zerocli.sh -f spice-vdagent.log

Encrypting data... [done]
[i] OK server returned code 200
Your data have been successfully pasted
url: https://xxx.xxx.com/?be1484a06a3c4ba0#zDeaHoSBsciAzKrji561wzsjIKWjDYy9PjVQG0/lkTY=
delete url: https://xxx.xxx.com/?pasteid=be1484a06a3c4ba0&deletetoken=3cf20bba0fb73dc0d77bfdbf562e671b06f4674d
```

Log files

```
[root@localhost log]# ls -la spice-vdagent.log yum.log
-rw-------. 1 root root   686 Mar 13 08:38 spice-vdagent.log
-rw-------. 1 root root 69419 May  1 09:19 yum.log
```

**Comment by ziirish** [comment]
Hi,

Actually there is no limitation on client-side but there might be one on server-side.

I could reproduce your issue and it was a bug in the code as you can see with the following trace:

[e] Error: server returned 100
200
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Server: nginx
Date: Sun, 05 May 2013 07:59:28 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.3.24-1~dotdeb.0

{"status":0,"id":"xxx","deletetoken":"yyy"}

When sending large data, the client or server (I' not really sure who does that) splits the request using the HTTP code 100.
I commited a patch so this problem should be solved now.

**Comment by TheFiZi** [comment]
Confirmed. Works like a charm now.
