### ISSUE TITLE
Bug with newer versions of v8?

### ISSUE THREAD

**Issue by TheFiZi** [ziirish/zerocli#9]
I have a CentOS system running v8 3.14.5.8 and zerocli works perfectly.

On my Mac OS system running v8 3.25.30 I get the following error

```
./zerocli zerocli.conf 

Encrypting data... [failed]
[e] Error: javascript engine returned code 1
/Users/schewee/scripts/zerocli/main.js:3: ReferenceError: arguments is not defined
l = arguments.length;
    ^
ReferenceError: arguments is not defined
    at /Users/schewee/scripts/zerocli/main.js:3:5
```

**Comment by ziirish** [comment]
Hi @TheFiZi,

Unfortunately, I cannot reproduce this issue.
Maybe that is something related with [this](https://code.google.com/p/v8/issues/detail?id=2103).

Anyway, as a workaround, you could try editing the configuration file to change the option `engineopts` this way:

```
#engineopts="-- v8"
engineopts="--js-arguments v8"
```

**Comment by TheFiZi** [comment]
Sorry I must have lost my notification for this. Will try that workaround when I get home and report back.

**Comment by TheFiZi** [comment]
Sadly no luck with that change

```
./zerocli zerocli.conf 

Encrypting data... [failed]
[e] Error: javascript engine returned code 1
/Users/schewee/scripts/zerocli/main.js:3: ReferenceError: arguments is not defined
l = arguments.length;
    ^
ReferenceError: arguments is not defined
    at /Users/schewee/scripts/zerocli/main.js:3:5
```

**Comment by ziirish** [comment]
Well, I'm afraid you'll have to recompile d8 without the `library=shared` option according to [this](https://github.com/joestelmach/lint.vim/issues/10#issuecomment-10216782).
You can also look [here](http://permalink.gmane.org/gmane.comp.lang.javascript.v8.general/6072)

**Comment by TheFiZi** [comment]
That did the trick. Thanks!
